### ISSUE TITLE
graphicsmagick not getting deployed on Heroku

### ISSUE THREAD

**Issue by achands** [mcollina/heroku-buildpack-graphicsmagick#10]
I am new to Heroku and am trying to deploy a nodejs application that uses https://github.com/samt/barcode which in turn uses graphicsmagick. My BUILDPACK_URL points to https://github.com/ddollar/heroku-buildpack-multi.git and .buildpacks file contains the following entries

https://github.com/mcollina/heroku-buildpack-graphicsmagick.git
https://github.com/heroku/heroku-buildpack-nodejs.git
https://github.com/heroku/heroku-buildpack-python.git

**Comment by benalavi** [comment]
cedar-14 support added in #12 so closing this issue.

I realize this is old but if you happen to still be using it on cedar-14 feel free to re-open not fixed for you.
