### ISSUE TITLE
gm convert: FreeType library is not available (font.otf) [No such file or directory].

### ISSUE THREAD

**Issue by magickaito** [mcollina/heroku-buildpack-graphicsmagick#22]
Using the same buildpack on cedar-14 giving me this error:

gm convert: FreeType library is not available (font.otf) [No such file or directory].

It appears that FreeType is disabled on cedar-14? gm -version shows this:

	GraphicsMagick 1.3.18 2013-03-10 Q8 http://www.GraphicsMagick.org/
	Copyright (C) 2002-2013 GraphicsMagick Group.
	Additional copyrights and licenses apply to this software.
	See http://www.GraphicsMagick.org/www/Copyright.html for details.

	Feature Support:
	Thread Safe              yes
	Large Files (> 32 bit)   yes
	Large Memory (> 32 bit)  yes
	BZIP                     yes
	DPS                      no
	FlashPix                 no
	FreeType                 no
	Ghostscript (Library)    no
	JBIG                     yes
	JPEG-2000                yes
	JPEG                     yes
	Little CMS               yes
	Loadable Modules         no
	OpenMP                   yes (201107)
	PNG                      yes
	TIFF                     yes
	TRIO                     no
	UMEM                     no
	WMF                      no
	X11                      yes
	XML                      yes
	ZLIB                     yes

	Host type: x86_64-unknown-linux-gnu

	Configured using the command:
	./configure  '--prefix' '/app/vendor/graphicsmagick'

	Final Build Parameters:
	CC       = gcc -std=gnu99
	CFLAGS   = -fopenmp -g -O2 -Wall -pthread
	CPPFLAGS = -I/usr/include/libxml2
	CXX      = g++
	CXXFLAGS = -pthread
	LDFLAGS  = -L/usr/lib -L/usr/lib
	LIBS     = -ljbig -llcms2 -ltiff -ljasper -ljpeg -lpng12 -lXext -lSM -lICE -lX11 -llzma -lbz2 -lxml2 -lz -lm -lgomp -lpthread

**Comment by magickaito** [comment]
This is what I get if I run gm -version on the old Cedar (freetype is yes):

    GraphicsMagick 1.3.18 2013-03-10 Q8 http://www.GraphicsMagick.org/
    Copyright (C) 2002-2013 GraphicsMagick Group.
    Additional copyrights and licenses apply to this software.
    See http://www.GraphicsMagick.org/www/Copyright.html for details.

    Feature Support:
    Thread Safe              yes
    Large Files (> 32 bit)   yes
    Large Memory (> 32 bit)  yes
    BZIP                     yes
    DPS                      no
    FlashPix                 no
    FreeType                 yes
    Ghostscript (Library)    no
    JBIG                     no
    JPEG-2000                yes
    JPEG                     yes
    Little CMS               yes
    Loadable Modules         no
    OpenMP                   yes (200805)
    PNG                      yes
    TIFF                     yes
    TRIO                     no
    UMEM                     no
    WMF                      yes
    X11                      yes
    XML                      yes
    ZLIB                     yes

    Host type: x86_64-unknown-linux-gnu

    Configured using the command:
    ./configure  '--prefix' '/app/vendor/graphicsmagick'

    Final Build Parameters:
    CC       = gcc -std=gnu99
    CFLAGS   = -fopenmp -g -O2 -Wall -pthread
    CPPFLAGS = -I/usr/include/freetype2 -I/usr/include/libxml2
    CXX      = g++
    CXXFLAGS = -pthread
    LDFLAGS  = -L/usr/lib -L/usr/lib
    LIBS     = -llcms -ltiff -lfreetype -ljasper -ljpeg -lpng12 -lwmflite -lXext -lSM -lICE -lX11 -lbz2 -lxml2 -lz -lm -lgomp -lpthread

**Comment by benalavi** [comment]
@magickaito Yeah I think you're right, some library on cedar probably installed freetype as a dependency which was removed on cedar-14. Will probably need to vendor the freetype lib now. If you want to take a stab at it feel free otherwise will play around with it in a bit.

**Comment by magickaito** [comment]
I am not familiar with buildpacks ... appreciate if you can help on this, thanks!

**Comment by benalavi** [comment]
Turns out was due to: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=731015#10 Updating graphicsmagick to 1.3.23 solved it as it properly references freetype2
