### ISSUE TITLE
Packaging tries to put files in `/app`

### ISSUE THREAD

**Issue by milgner** [mcollina/heroku-buildpack-graphicsmagick#26]
I'm just trying to create a build using updated versions of graphicsmagick, nasm and libpng.

The packaging process tries to put stuff in `/app` which of course is not present on my system. Is one supposed to execute the `support/package_graphicsmagick` script from the Vagrant machine, too?

Otherwise I'd propose `make install`ing the files into a fake root directory instead and creating the packages from there.

**Comment by benalavi** [comment]
@milgner Yeah you'll want to compile and package the libraries on a heroku dyno or on the vagrant VM (which is essentially a heroku dyno) so they compile with the same libraries available on heroku.

**Comment by milgner** [comment]
Alright, thanks for the tip!
