### ISSUE TITLE
GM can't be updated using `package_graphicsmagick` due to deprecated Vulcan

### ISSUE THREAD

**Issue by RobbinHabermehl** [mcollina/heroku-buildpack-graphicsmagick#8]
Vulcan has been [deprecated](https://github.com/heroku/vulcan#vulcan-deprecated), which disables the possibility of packaging a more recent version of GraphicsMagick as `./support/package_graphicsmagick` relies heavily on Vulcan.

While deprecated, Vulcan could still be used in fact. However, it does require the Heroku add-on "Cloudant" that isn't available anymore.

Heroku recommends using `heroku run` like [described by SendGrid](https://sendgrid.com/blog/create-first-heroku-buildpack/). Another approach would be [to use Docker](http://friism.com/building-heroku-buildpack-binaries-with-docker).

---

[![](https://www.bountysource.com/badge/issue?issue_id=5110170)](https://www.bountysource.com/issues/5110170-gm-can-t-be-updated-using-package_graphicsmagick-due-to-deprecated-vulcan)

**Comment by benalavi** [comment]
@mcollina @paolochiodi I removed the vulcan dependency and re-built/packaged everything for cedar-14 on my fork here: https://github.com/mcollina/heroku-buildpack-graphicsmagick/compare/master...benalavi:master

I can send a pull request but had some questions/explanation first:

The packages for cedar-14 don't work on cedar. To fix that I guess would either have to figure out how to make packages that work for both (sounds difficult) or maintain 2 sets of packages. Heroku always sets `STACK` on the environment while building so could use that to switch between which set to download, but maintaining 2 builds is obviously less fun. Any ideas?

I actually built this using a Vagrant VM provisioned w/ Heroku's cedar-14 script, that's what that Vagrantfile is doing in there. It's not totally necessary -- the package script also works on Heroku itself, but I thought it might be useful.

My bash isn't fantastic so my changes to the package script might be dumb, but they work.

Finally, I'm using this for work currently so will continue to maintain it for the time being.

**Comment by mcollina** [comment]
@benalavi __THIS IS AWESOME__ I am adding you to the list of contributors!

I will discuss the double build in the PR.

**Comment by RobbinHabermehl** [comment]
Great @benalavi! I'm looking forward to implementing the final result.

And good for you, the [bounty](https://www.bountysource.com/issues/5110170-gm-can-t-be-updated-using-package_graphicsmagick-due-to-deprecated-vulcan) can finally be paid then! ;)

**Comment by benalavi** [comment]
@RobbinHabermehl merged in #12 adding the cedar-14 support so going to close this issue, but feel free to re-open if it doesn't work for you.

I would feel bad taking a bounty as I did this for work! :)

**Comment by RobbinHabermehl** [comment]
@benalavi, I'll update my buildpack tonight and testing is planned for tomorrow, I'll provide my feedback anyway.

And you shouldn't feel bad about taking the bounty, it's praiseworthy that something developed in work time is being open sourced. Just buy your colleagues beer, or if you feel really bad about it you can always donate it to charity!
