### ISSUE TITLE
Upload 1.3.20 tgz to heroku-buildpack-graphicsmagick s3 acccount

### ISSUE THREAD

**Issue by tomdmaguire** [mcollina/heroku-buildpack-graphicsmagick#9]
Hey,

I have created a tgz of gm 1.3.20. Are you the owner of the heroku-buildpack-graphicsmagick s3 bucket? If so, would you like me to send over the file so you can uploaded it for all to use?

**Comment by Dhaulagiri** [comment]
@tomdmaguire did you ever figure out how to get this working? Or did you just maintain a separate S3 bucket with these libraries?  We are using the current version of the buildpack and finding its performance to be quite slow compared with similar operations locally.

**Comment by tomdmaguire** [comment]
@Dhaulagiri we ended up using this fork which ships with 1.3.20 https://github.com/RobbinHabermehl/heroku-buildpack-graphicsmagick

**Comment by benalavi** [comment]
Well exactly a year later gm is at 1.3.23 now -- however I'm not sure entirely sure that the old related libraries are (or ever were for cedar-14) correctly linked. Also not sure what difference they make on cedar-14 but might be worth testing.
